"""Generate a deterministic route set from a demand configuration.

Two stages, both reproducible from committed inputs:

1. Write flow definitions — ``<flow>`` elements between boundary edges, split
   across vehicle types by the configured mix — into ``simulation/demand/``.
2. Route them with ``duarouter``, which computes an actual path over the network
   for every vehicle and **fails on any origin-destination pair it cannot
   connect**. That failure is the point: it is where an unroutable pair is caught,
   before a simulation quietly drops the vehicles.

``--ignore-errors`` is deliberately not used. A demand set with silently missing
vehicles produces a network that looks less congested than it was configured to
be, and nothing downstream would notice.

Determinism comes from the seed being passed to duarouter and from the flow
definitions being written in a fixed order. The same config produces the same
route file, which a test asserts by hashing it.
"""

from __future__ import annotations

import subprocess
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from ems_sim.demand.ambulance import AmbulanceTripConfig
from ems_sim.demand.config import DemandConfig
from ems_sim.demand.vehicle_types import vehicle_types_xml
from ems_sim.runner.sumo_env import SumoInstallation, require_sumo


class DemandGenerationError(RuntimeError):
    """Raised when a demand set cannot be produced honestly."""


@dataclass
class GeneratedDemand:
    """The artefacts one generation run produced."""

    flows_file: Path
    routes_file: Path
    config: DemandConfig
    ambulance: AmbulanceTripConfig
    duarouter_command: list[str]
    duarouter_warnings: list[str] = field(default_factory=list)
    vehicle_count: int = 0
    vehicles_by_type: dict[str, int] = field(default_factory=dict)
    ambulance_route_edges: list[str] = field(default_factory=list)
    discarded_vehicles: int = 0

    def as_dict(self) -> dict[str, Any]:
        return {
            "flows_file": str(self.flows_file),
            "routes_file": str(self.routes_file),
            "vehicle_count": self.vehicle_count,
            "vehicles_by_type": self.vehicles_by_type,
            "discarded_vehicles": self.discarded_vehicles,
            "ambulance_route_edge_count": len(self.ambulance_route_edges),
            "duarouter_command": self.duarouter_command,
            "duarouter_warning_count": len(self.duarouter_warnings),
        }


def write_flows(
    config: DemandConfig,
    ambulance: AmbulanceTripConfig,
    destination: Path,
    vtype_overrides: dict[str, dict[str, float | str]] | None = None,
) -> Path:
    """Write the flow definitions and the ambulance trip.

    Each configured OD flow is split across vehicle types by the mix, producing
    one ``<flow>`` per (OD pair, type). Splitting here rather than using a type
    distribution keeps the per-type rate visible in the file, so a reader can see
    how many buses the configuration asks for without running anything.
    """
    lines: list[str] = [
        "<?xml version='1.0' encoding='UTF-8'?>",
        "",
        "<!--",
        f"  EMS Black Box baseline demand — {config.demand_id}",
        "",
        f"  period {config.period}  seed {config.seed}  hash {config.config_hash()}",
        f"  window {config.begin_s:.0f}-{config.end_s:.0f} s (warm-up {config.warmup_s:.0f} s)",
        "",
        "  ESTIMATED_DATA. Flow rates and vehicle mix are assumptions made by this",
        "  project, not measured Bengaluru traffic counts. Vehicles produced by",
        "  simulating this file are SIMULATED_DATA. See docs/TRAFFIC_DEMAND.md.",
        "",
        "  Generated by ems_sim.demand.generator. Do not edit by hand: an edited",
        "  demand file has no provenance and its results cannot be defended.",
        "-->",
        "",
        "<routes xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'"
        " xsi:noNamespaceSchemaLocation='http://sumo.dlr.de/xsd/routes_file.xsd'>",
        "",
        "    <!-- Vehicle types. Every parameter is ESTIMATED_DATA; see",
        "         ems_sim.demand.vehicle_types for the basis of each. -->",
        *(
            [
                "    <!-- SENSITIVITY EXPERIMENT: these vTypes carry deliberate",
                f"         overrides, NOT the committed baseline: {vtype_overrides} -->",
            ]
            if vtype_overrides
            else []
        ),
        vehicle_types_xml(vtype_overrides),
        "",
        "    <!-- Background traffic: boundary source -> boundary sink. -->",
    ]

    index = 0
    for flow in config.scaled_flows():
        for type_id, share in sorted(config.vehicle_mix.items()):
            rate = flow.vehicles_per_hour * share
            if rate <= 0:
                continue
            flow_id = f"f{index:03d}_{type_id}"
            index += 1
            lines.append(
                f'    <flow id="{flow_id}" type="{type_id}" '
                f'begin="{config.begin_s:.1f}" end="{config.end_s:.1f}" '
                f'from="{flow.from_edge}" to="{flow.to_edge}" '
                f'vehsPerHour="{rate:.4f}" departLane="best" departSpeed="max"/>'
            )
        lines.append(f"    <!-- {flow.label}: {flow.vehicles_per_hour:.1f} veh/h total -->")

    lines += [
        "",
        "    <!-- The ambulance. An ordinary vehicle in this phase: no siren, no",
        "         signal preemption, no speed bonus. Phase 5 adds priority; the",
        "         baseline must not already carry any, or the recovered time it",
        "         is subtracted from would be understated. -->",
        f'    <trip id="{ambulance.vehicle_id}" type="{ambulance.vehicle_type}" '
        f'depart="{ambulance.depart_time_s:.1f}" '
        f'from="{ambulance.origin_edge}" to="{ambulance.destination_edge}" '
        f'departLane="best" departSpeed="max"/>',
        "",
        "</routes>",
    ]

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return destination


def run_duarouter(
    net_file: Path,
    flows_file: Path,
    routes_file: Path,
    config: DemandConfig,
    repo_root: Path,
    installation: SumoInstallation | None = None,
) -> tuple[list[str], list[str]]:
    """Route the demand, refusing to discard anything it cannot connect.

    Returns ``(command, warnings)``.
    """
    installation = installation or require_sumo()
    binary = installation.binary("duarouter")
    routes_file.parent.mkdir(parents=True, exist_ok=True)

    command = [
        str(binary),
        "--net-file",
        str(net_file),
        "--route-files",
        str(flows_file),
        "--output-file",
        str(routes_file),
        "--seed",
        str(config.seed),
        # Vehicles are written sorted by departure so the output is stable
        # independent of routing order — a precondition for hashing it.
        "--departlane",
        "best",
        "--departspeed",
        "max",
        # No --ignore-errors and no --repair: an OD pair that cannot be
        # connected is a finding about the network, not something to paper over.
        "--verbose",
        "--no-step-log",
    ]
    completed = subprocess.run(
        command,
        capture_output=True,
        text=True,
        cwd=repo_root,
        env={"SUMO_HOME": str(installation.home), "PATH": "/usr/bin:/bin"},
        check=False,
    )
    combined = completed.stdout + "\n" + completed.stderr
    warnings = [ln.strip() for ln in combined.splitlines() if ln.strip().startswith("Warning:")]
    errors = [ln.strip() for ln in combined.splitlines() if ln.strip().startswith("Error:")]

    if completed.returncode != 0 or not routes_file.is_file():
        detail = "\n  ".join(errors[:10]) or completed.stderr[-2000:]
        raise DemandGenerationError(
            f"duarouter failed (exit {completed.returncode}). No routes were written.\n"
            f"  command: {' '.join(command)}\n  {detail}"
        )
    return command, warnings


def summarise_routes(
    routes_file: Path, ambulance: AmbulanceTripConfig
) -> tuple[int, dict[str, int], list[str]]:
    """Count what duarouter produced and extract the ambulance's route."""
    root = ET.parse(routes_file).getroot()
    by_type: dict[str, int] = {}
    ambulance_edges: list[str] = []
    total = 0
    for vehicle in root.findall("vehicle"):
        total += 1
        type_id = vehicle.get("type", "?")
        by_type[type_id] = by_type.get(type_id, 0) + 1
        if vehicle.get("id") == ambulance.vehicle_id:
            route = vehicle.find("route")
            if route is not None:
                ambulance_edges = (route.get("edges") or "").split()
    return total, dict(sorted(by_type.items())), ambulance_edges


def generate_demand(
    config: DemandConfig,
    ambulance: AmbulanceTripConfig,
    net_file: Path,
    repo_root: Path,
    installation: SumoInstallation | None = None,
    vtype_overrides: dict[str, dict[str, float | str]] | None = None,
) -> GeneratedDemand:
    """Write flows, route them, and summarise the result."""
    installation = installation or require_sumo()
    flows_file = repo_root / "simulation" / "demand" / f"{config.demand_id}.flows.xml"
    routes_file = repo_root / "simulation" / "routes" / f"{config.demand_id}.rou.xml"

    write_flows(config, ambulance, flows_file, vtype_overrides)
    command, warnings = run_duarouter(
        net_file, flows_file, routes_file, config, repo_root, installation
    )
    total, by_type, ambulance_edges = summarise_routes(routes_file, ambulance)

    if not ambulance_edges:
        raise DemandGenerationError(
            f"duarouter produced no route for {ambulance.vehicle_id} "
            f"({ambulance.origin_edge} -> {ambulance.destination_edge}). The trip "
            f"cannot be simulated, and reporting a travel time for it would be "
            f"reporting a number for a journey that never happened."
        )

    return GeneratedDemand(
        flows_file=flows_file,
        routes_file=routes_file,
        config=config,
        ambulance=ambulance,
        duarouter_command=command,
        duarouter_warnings=warnings,
        vehicle_count=total,
        vehicles_by_type=by_type,
        ambulance_route_edges=ambulance_edges,
    )
