#!/usr/bin/env python3
"""Re-analyse the frozen counterfactual matrix over a properly paired vehicle cohort.

    python scripts/analyse_paired_cohort.py                  # the incident scenario
    python scripts/analyse_paired_cohort.py --prefix two_signal_

Reads the committed per-run records, the demand each run was given, and the
tripinfo SUMO wrote, and reports what became of **every** generated vehicle in
each arm before it computes any traffic metric. See
``ems_sim.counterfactual.cohort`` for why that order matters.

Re-runs nothing. The runs analysed here are the same runs the published numbers
came from, so a difference between this analysis and the published one is a
difference in the analysis, not in the simulation.

Writes ``data/processed/<area>/paired_cohort_<prefix>.json``.
"""

from __future__ import annotations

import argparse
import json
import statistics
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT / "simulation") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "simulation"))

from ems_sim.counterfactual.cohort import (  # noqa: E402
    RunCohort,
    completed_trips,
    generated_vehicles,
    paired_cohort,
)
from ems_sim.provenance import utc_now_iso  # noqa: E402

BASELINE_POLICY = "NORMAL"


def load_run(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def build_cohort(record: dict, routes_file: Path, tripinfo: Path, ambulance_id: str) -> RunCohort:
    run = record["run"]
    teleports = run["simulation"]["teleports"]
    if len(teleports["events"]) < teleports["count"]:
        raise SystemExit(
            f"{tripinfo}: the record lists {len(teleports['events'])} of "
            f"{teleports['count']} teleports, so the teleported set cannot be "
            f"reconstructed. Re-run this scenario before analysing it."
        )
    return RunCohort(
        policy=run["policy"],
        seed=run["seed"],
        generated=generated_vehicles(routes_file),
        trips=completed_trips(tripinfo),
        teleported_ids={event["vehicle_id"] for event in teleports["events"]},
        never_departed_count=run["simulation"]["vehicles"]["insertion_backlog_at_end"],
        ambulance_id=ambulance_id,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--area", default="silk_board_v1")
    parser.add_argument(
        "--prefix",
        default="inc_two_signal_",
        help="Result-file prefix identifying the scenario (default: the incident matrix).",
    )
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args()

    results = REPO_ROOT / "data" / "processed" / args.area / "counterfactual"
    records: dict[tuple[int, str], dict] = {}
    for path in sorted(results.glob(f"{args.prefix}seed*.json")):
        if path.stem.endswith("_comparisons"):
            continue
        record = load_run(path)
        run = record["run"]
        records[(run["seed"], run["policy"])] = record
    if not records:
        raise SystemExit(f"No run records matching {args.prefix!r} under {results}")

    seeds = sorted({seed for seed, _ in records})
    policies = sorted({policy for _, policy in records if policy != BASELINE_POLICY})

    pairs: list[dict] = []
    for seed in seeds:
        baseline_record = records.get((seed, BASELINE_POLICY))
        if baseline_record is None:
            raise SystemExit(f"Seed {seed} has no {BASELINE_POLICY} run to pair against.")
        baseline_run = baseline_record["run"]
        demand_id = baseline_record["reproducibility"]["scenario"]["demand_id"]
        routes_file = REPO_ROOT / "simulation" / "routes" / f"{demand_id}.rou.xml"
        if not routes_file.is_file():
            raise SystemExit(
                f"{routes_file} is missing. It is the denominator of this analysis — "
                f"the vehicles both arms were given — and is regenerated by "
                f"scripts/run_counterfactual.py for this demand id."
            )
        # Read the ambulance's id out of the demand rather than guessing at the
        # spelling of the trip label: it is excluded from every traffic metric,
        # and excluding the wrong vehicle would leave it in one.
        generated = generated_vehicles(routes_file)
        ambulance_ids = [v for v in generated if v.startswith("ambulance")]
        if len(ambulance_ids) != 1:
            raise SystemExit(f"{routes_file} has {len(ambulance_ids)} ambulances; expected 1.")
        ambulance_id = ambulance_ids[0]

        baseline_tripinfo = REPO_ROOT / baseline_run["output_dir"] / "tripinfo.xml"
        if not baseline_tripinfo.is_file():
            raise SystemExit(f"{baseline_tripinfo} is missing; re-run the matrix.")
        baseline_cohort = build_cohort(
            baseline_record, routes_file, baseline_tripinfo, ambulance_id
        )

        for policy in policies:
            record = records.get((seed, policy))
            if record is None:
                continue
            tripinfo = REPO_ROOT / record["run"]["output_dir"] / "tripinfo.xml"
            if not tripinfo.is_file():
                raise SystemExit(f"{tripinfo} is missing; re-run the matrix.")
            cohort = build_cohort(record, routes_file, tripinfo, ambulance_id)
            pair = paired_cohort(baseline_cohort, cohort)
            pair["scenario_hash"] = baseline_record["reproducibility"]["scenario_hash"]
            pair["policy_scenario_hash"] = record["reproducibility"]["scenario_hash"]
            pairs.append(pair)

    # Across-seed summary of the one view that supports a causal claim, with the
    # biased view beside it so the size and direction of the bias are visible.
    summary: dict[str, dict] = {}
    sign_flips = 0
    for policy in policies:
        rows = [p for p in pairs if p["counterfactual_policy"] == policy]
        per_seed = []
        for row in rows:
            biased = row["views"]["all_completed"]["deltas"]["time_loss_s"]["total"]["absolute"]
            mean = row["views"]["paired_common_cohort"]["deltas"]["time_loss_s"]["mean"][
                "absolute"
            ]
            paired_total = round(mean * row["paired_count"], 1)
            flipped = (biased > 0) != (paired_total > 0)
            sign_flips += int(flipped)
            per_seed.append(
                {
                    "seed": row["seed"],
                    "paired_cohort_size": row["paired_count"],
                    "paired_mean_time_loss_delta_s_per_vehicle": mean,
                    "paired_total_time_loss_delta_s": paired_total,
                    "survivorship_biased_total_time_loss_delta_s": biased,
                    "bias_s": round(biased - paired_total, 1),
                    "sign_differs_from_biased_view": flipped,
                    "unfinished_delta_policy_minus_normal": row["censored"][
                        "unfinished_delta_policy_minus_normal"
                    ],
                }
            )
        means = [row["paired_mean_time_loss_delta_s_per_vehicle"] for row in per_seed]
        spread = statistics.stdev(means) if len(means) > 1 else None
        summary[policy] = {
            "seeds": len(rows),
            "per_seed": per_seed,
            "paired_mean_time_loss_delta_s_per_vehicle": {
                "mean": round(statistics.fmean(means), 3) if means else None,
                "stdev": round(spread, 3) if spread is not None else None,
                "min": round(min(means), 3) if means else None,
                "max": round(max(means), 3) if means else None,
                "standard_error": (
                    round(spread / (len(means) ** 0.5), 3) if spread is not None else None
                ),
            },
            "distinguishable_from_zero": (
                bool(means)
                and spread is not None
                and abs(statistics.fmean(means)) > 2 * spread / (len(means) ** 0.5)
            ),
        }

    payload = {
        "generated_at": utc_now_iso(),
        "area": args.area,
        "scenario_prefix": args.prefix,
        "seeds": seeds,
        "policies": policies,
        "baseline_policy": BASELINE_POLICY,
        "method": (
            "Every generated vehicle is classified in both arms before any metric "
            "is computed. Travel-time metrics exclude teleported trips. The paired "
            "common cohort — vehicles that completed without a teleport in both "
            "arms — is the only view valid for a causal claim; the survivorship-"
            "biased view is reported beside it so the size of the bias is visible."
        ),
        "reanalysis_of": "frozen runs; no simulation was re-run",
        "sign_flips_vs_biased_view": sign_flips,
        "summary": summary,
        "pairs": pairs,
        "data_class": "SIMULATED_DATA",
    }
    out = args.out or (
        REPO_ROOT
        / "data"
        / "processed"
        / args.area
        / f"paired_cohort_{args.prefix.rstrip('_')}.json"
    )
    out.write_text(json.dumps(payload, indent=2) + "\n")

    print(f"{len(pairs)} pairs over {len(seeds)} seeds -> {out.relative_to(REPO_ROOT)}")
    print(f"sign flips between the biased and the paired view: {sign_flips} of {len(pairs)}")
    for policy, row in summary.items():
        stats = row["paired_mean_time_loss_delta_s_per_vehicle"]
        print(f"\n  {policy}")
        header = f"    {'seed':>5} {'paired n':>9} {'biased':>13} {'paired':>13} {'unfin d':>8}"
        print(header)
        for seed_row in row["per_seed"]:
            print(
                f"    {seed_row['seed']:>5} {seed_row['paired_cohort_size']:>9} "
                f"{seed_row['survivorship_biased_total_time_loss_delta_s']:>13.0f} "
                f"{seed_row['paired_total_time_loss_delta_s']:>13.0f} "
                f"{seed_row['unfinished_delta_policy_minus_normal']:>8}"
                + ("   SIGN FLIP" if seed_row["sign_differs_from_biased_view"] else "")
            )
        verdict = (
            "distinguishable from zero"
            if row["distinguishable_from_zero"]
            else "NOT distinguishable from zero"
        )
        print(
            f"    paired per-vehicle delta: mean {stats['mean']:+.2f} s, "
            f"sd {stats['stdev']:.2f}, se {stats['standard_error']:.2f} -> {verdict}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
