#!/usr/bin/env python3
"""Phase 4: audit the network's estimated parameters.

    python scripts/audit_baseline.py

Writes two machine-readable reports and changes nothing:

* ``calibration/signal_programs.json`` — every traffic-light program, labelled
  ESTIMATED_DATA / NETCONVERT_GENERATED.
* ``calibration/speed_provenance.json`` — every edge's speed, separated into
  OSM-derived and SUMO-estimated.

Both exist because Phase 3's results rest on assumptions that stop looking like
assumptions once they are inside a `.net.xml`, and a number that has been through
a simulation looks like a measurement whether or not it started as one.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT / "simulation") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "simulation"))

from ems_sim.calibration.audits import audit_speeds, audit_traffic_lights  # noqa: E402
from ems_sim.calibration.scenario import DEFAULT_VARIANT  # noqa: E402
from ems_sim.provenance import (  # noqa: E402
    DataClass,
    ProvenanceRecord,
    sha256_file,
    utc_now_iso,
    write_record,
)
from ems_sim.runner.sumo_env import require_sumo  # noqa: E402


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--area", default="silk_board_v1")
    args = parser.parse_args()

    installation = require_sumo()
    net_file = DEFAULT_VARIANT.net_file(REPO_ROOT, args.area)
    if not net_file.is_file():
        print(f"error: {net_file.relative_to(REPO_ROOT)} not found.", file=sys.stderr)
        return 2

    calib = REPO_ROOT / "data" / "processed" / args.area / "calibration"
    calib.mkdir(parents=True, exist_ok=True)

    reproducibility = {
        "generated_at": utc_now_iso(),
        "sumo_version": installation.version,
        "network_file": str(net_file.relative_to(REPO_ROOT)),
        "network_sha256": sha256_file(net_file),
        "scenario_variant": DEFAULT_VARIANT.as_dict(),
    }

    signals = audit_traffic_lights(net_file)
    speeds = audit_speeds(net_file)

    (calib / "signal_programs.json").write_text(
        json.dumps({"reproducibility": reproducibility, "audit": signals}, indent=2) + "\n",
        encoding="utf-8",
    )
    (calib / "speed_provenance.json").write_text(
        json.dumps({"reproducibility": reproducibility, "audit": speeds}, indent=2) + "\n",
        encoding="utf-8",
    )

    write_record(
        ProvenanceRecord(
            dataset_id="phase4_parameter_audit",
            data_class=DataClass.ESTIMATED,
            description=(
                "Phase 4 audit of the network's estimated parameters: every "
                "traffic-light program and every edge speed, separated by "
                "provenance."
            ),
            estimation_basis=(
                "The audit reads the converted network and reports what is there. "
                "The parameters it describes are estimates: traffic-light programs "
                "were generated by netconvert from its defaults, and edge speeds "
                "were supplied by its type map wherever OpenStreetMap had none. "
                "Nothing was changed, and no external source was consulted."
            ),
            source_name="EMS Black Box Phase 4 audit",
            retrieved_at=utc_now_iso(),
            file_path=str((calib / "signal_programs.json").relative_to(REPO_ROOT)),
            derived_from=["silk_board_v1_sumo_network", "sumo_network_review"],
            processing_steps=[
                "Enumerated every tlLogic: phases, cycle length, green/yellow/"
                "all-red split, and green share per signal group.",
                "Classified every edge's speed as OSM-derived or SUMO-estimated "
                "using the osmDefaults parameter netconvert writes.",
                "Isolated edges given a default speed at or above 80 km/h.",
            ],
            tool_versions={"sumo": installation.version or "unknown"},
            limitations=[
                "TRAFFIC-LIGHT TIMINGS ARE NOT BENGALURU TIMINGS. Signal locations "
                "come from OSM; timings do not exist in OSM and are not published "
                "for Bengaluru. Every phase duration here is a netconvert default.",
                f"{speeds['sumo_estimated']['edge_count']} of {speeds['total_edges']} "
                "edges carry a SUMO-supplied free-flow speed. Time loss is measured "
                "against free-flow, so reported time loss is an over-estimate where "
                "the default exceeds the real limit.",
                f"{speeds['high_speed_defaults']['count']} edges were given a default "
                "of 80 km/h or more by a type map derived from European conventions.",
                "Nothing was replaced. No source in this project supports better "
                "values, and a guess would look sourced while losing its provenance.",
            ],
            notes=(
                f"{signals['traffic_light_count']} traffic lights, all "
                f"{'static' if signals['all_static'] else 'mixed type'}, cycle "
                f"{signals['cycle_lengths_s']}s."
            ),
        ),
        REPO_ROOT / "data" / "provenance",
    )

    print(
        f"Traffic lights: {signals['traffic_light_count']} "
        f"({'all static' if signals['all_static'] else 'mixed'}), "
        f"cycles {signals['cycle_lengths_s']}s, phases {signals['phase_counts']}"
    )
    meaningful = [
        p
        for p in signals["programs"]
        if p["green_share_per_signal_group"] and p["green_share_per_signal_group"]["min"] < 0.8
    ]
    print(
        f"  actually controlling conflicting movements: {len(meaningful)} "
        f"(the rest give ~90% green to one or two groups)"
    )
    print(
        f"\nSpeeds: {speeds['osm_derived']['edge_count']} OSM-derived, "
        f"{speeds['sumo_estimated']['edge_count']} SUMO-estimated"
    )
    high = speeds["high_speed_defaults"]
    print(
        f"  >= {high['threshold_kmh']:.0f} km/h by default: {high['count']} edges, "
        f"{high['total_length_km']} km, {high['by_edge_class']}"
    )
    print(f"\nwrote {(calib / 'signal_programs.json').relative_to(REPO_ROOT)}")
    print(f"wrote {(calib / 'speed_provenance.json').relative_to(REPO_ROOT)}")
    print("\nESTIMATED_DATA / NETCONVERT_GENERATED. Not Bengaluru signal timings.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
