#!/usr/bin/env python3
"""Phase 2.5 entry point: print the human-facing review of the SUMO network.

    python scripts/review_sumo_network.py            # full review
    python scripts/review_sumo_network.py --section tls

The review is regenerated by ``scripts/build_sumo_network.py`` as part of the
build and written to ``data/processed/<area>/network_review.json``. This script
reads that file and renders it for a person, so it never disagrees with the
machine-readable record.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT / "simulation") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "simulation"))

from ems_sim.network.study_area import STUDY_AREAS, get_study_area  # noqa: E402

SECTIONS = ("operational", "boundary", "tls", "ramps", "junctions", "defaults")


def _operational(review: dict) -> None:
    findings = review["operational_status"]
    print(f"\n=== 1. OPERATIONAL STATUS ({len(findings)} flagged ways) ===")
    for status in ("UNRESOLVED", "NOT_OPERATIONAL", "OPERATIONAL"):
        group = [f for f in findings if f["status"] == status]
        if not group:
            continue
        print(f"\n  {status}: {len(group)}")
        for f in group:
            marker = " [IN DRIVABLE NETWORK]" if f["in_drivable_network"] else ""
            print(
                f"    way/{f['osm_way_id']:<12} {f['highway']:16} "
                f"{f['name'] or '(unnamed)'}{marker}"
            )
            if status != "OPERATIONAL":
                for e in f["evidence_against_operational"]:
                    print(f"        against: {e}")
                for e in f["evidence_for_operational"][:3]:
                    print(f"        for    : {e}")
            if f["sumo_edges"]:
                print(f"        SUMO edges: {f['sumo_edges']}")
            if f["removal_would_disconnect"]:
                print(f"        removing it would isolate: {f['removal_would_disconnect']}")
            if f["verification_needed"]:
                print(f"        NEEDS: {f['verification_needed']}")


def _boundary(review: dict) -> None:
    print("\n=== 2. DISCONNECTED FRAGMENTS ===")
    for way_id, payload in review["boundary_disconnection"].items():
        print(f"\n  way/{way_id} — {payload.get('name')} ({payload.get('highway')})")
        print(f"    cause: {payload.get('cause')}")
        print(f"    {payload.get('explanation')}")
        print(
            f"    nearest connection to a study-area edge: "
            f"{payload.get('nearest_connection_to_study_edge_m')} m"
        )
        print(f"    route generation: {payload.get('affects_route_generation')}")
        for n in payload.get("neighbours_in_source", []):
            print(
                f"      neighbour way/{n['osm_way_id']:<12} {str(n['highway']):12} "
                f"survived={n['survived_conversion']}"
            )


def _tls(review: dict) -> None:
    lights = review["traffic_lights"]
    print(f"\n=== 3. TRAFFIC LIGHTS ({len(lights)} built) ===")
    for light in sorted(lights, key=lambda t: -t["controlled_links"]):
        print(f"\n  {light['tls_id']}")
        print(f"    ({light['lat']}, {light['lon']}) in_study_area={light['inside_study_area']}")
        print(
            f"    controls {light['controlled_links']} links on "
            f"{light['road_names'] or ['(unnamed)']}"
        )
        print(f"    OSM signal nodes within 75 m: {light['osm_signal_nodes_within_75m'] or 'NONE'}")
        print(f"    {light['plausibility']}: {light['plausibility_reason']}")
    orphans = review["orphan_signal_nodes"]
    print(f"\n  OSM signal nodes with no traffic light ({len(orphans)}):")
    for o in orphans:
        print(
            f"    node/{o['osm_node_id']:<13} in_study_area={o['inside_study_area']} "
            f"nearest TLS {o['nearest_tls_m']} m — {o['reason']}"
        )
    frag = review["tls_fragmentation"]
    print(
        f"\n  {frag['traffic_lights_in_study_area']} lights in the study area group into "
        f"{frag['probable_physical_intersections']} physical intersections "
        f"at {frag['colocation_radius_m']:.0f} m:"
    )
    for f in frag["fragmented_intersections"]:
        print(
            f"    {f['count']} lights, {f['total_links']} links, "
            f"max separation {f['max_separation_m']} m, roads={f['road_names']}"
        )
        for t in f["tls_ids"]:
            print(f"       - {t}")


def _ramps(review: dict) -> None:
    ramp = review["ramp_connectivity"]
    print(
        f"\n=== 4. FLYOVER / RAMP CONNECTIVITY "
        f"({ramp['major_deck_edges']} major decks, {ramp['ramp_edges']} ramps) ==="
    )
    print(f"  {ramp['invariant_note']}")
    for deck in ramp["decks"]:
        print(
            f"\n  {deck['edge_id']:14} L{deck['layer']} {deck['length_m']:8.1f} m  "
            f"{deck['name'] or '(unnamed)'}"
        )
        for direction in ("incoming", "outgoing"):
            entries = deck[direction]
            print(
                f"    {direction:8}: "
                + (", ".join(f"{e['edge']}[{e['kind']}]" for e in entries) if entries else "NONE")
            )
    print(f"\n  suspicious cross-connections: {ramp['suspicious_cross_connections'] or 'none'}")
    print("  boundary terminal decks (legitimate source/sink at a clipped edge):")
    for d in ramp["boundary_terminal_decks"]:
        print(f"    {d['edge_id']:14} {d['length_m']:8.1f} m  {d['role']}  {d['name'] or ''}")
    print(f"  dangling ramps: {[d['edge_id'] for d in ramp['dangling_ramps']] or 'none'}")


def _junctions(review: dict) -> None:
    merges = review["junction_merges"]
    print(f"\n=== 5. JUNCTION JOINING ({merges['joined_clusters']} joined clusters) ===")
    print(
        f"  clusters merging a grade separation: "
        f"{[c['junction_id'] for c in merges['clusters_merging_grade_separation']] or 'NONE'}"
    )
    print(
        f"  clusters spanning layers but correct (bridge meets its approaches): "
        f"{len(merges['clusters_spanning_layers'])}"
    )
    print(f"  legitimate single-sided layer transitions: {merges['legitimate_layer_transitions']}")
    print(
        f"  through-traffic at two levels: {merges['major_severity_count']} MAJOR, "
        f"{merges['minor_severity_count']} MINOR"
    )
    for f in merges["through_traffic_at_two_levels"]:
        if f["severity"] == "MAJOR":
            print(
                f"    MAJOR {f['junction_id']} {f['road_names']} "
                f"crosses_in_interior={f['crosses_in_interior']}"
            )
    print("\n  joined clusters carrying a traffic light:")
    for c in merges["joined_cluster_detail"]:
        if c["is_traffic_light"]:
            print(
                f"    {c['junction_id'][:60]:62} in={c['incoming']} out={c['outgoing']} "
                f"roads={c['road_names']}"
            )


def _defaults(review: dict) -> None:
    d = review["defaults"]
    print(f"\n=== 6. DEFAULTED LANES / SPEEDS ({d['data_class']}) ===")
    print(f"  total edges                : {d['total_edges']}")
    print(f"  fully OSM-sourced          : {d['edges_fully_osm_sourced']}")
    print(f"  lane count defaulted       : {d['lanes_defaulted']}")
    print(f"  speed defaulted            : {d['speed_defaulted']}")
    print(f"\n  speed histogram (km/h), defaulted: {d['speed_histogram_kmh']['defaulted']}")
    print(f"  speed histogram (km/h), from OSM : {d['speed_histogram_kmh']['from_osm']}")
    print(f"\n  lanes histogram, defaulted: {d['lane_histogram']['defaulted']}")
    print(f"  lanes histogram, from OSM : {d['lane_histogram']['from_osm']}")
    print("\n  by road class (defaulted / total):")
    for cls, stats in d["by_road_class"].items():
        print(
            f"    {cls:26} lanes {stats['lanes_defaulted']:5d}/{stats['edges']:<5d} "
            f"speed {stats['speed_defaulted']:5d}/{stats['edges']}"
        )
    imp = d["implausible_default_speeds"]
    print(f"\n  default speeds >= {imp['threshold_kmh']:.0f} km/h: {imp['count']} edges")
    print(f"    {imp['note']}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--area", default="silk_board_v1", choices=sorted(STUDY_AREAS))
    parser.add_argument("--section", choices=SECTIONS, action="append")
    args = parser.parse_args()

    area = get_study_area(args.area)
    path = REPO_ROOT / "data" / "processed" / area.area_id / "network_review.json"
    if not path.is_file():
        print(
            f"error: {path.relative_to(REPO_ROOT)} not found."
            " Run scripts/build_sumo_network.py first.",
            file=sys.stderr,
        )
        return 2

    review = json.loads(path.read_text())
    print(f"Phase 2.5 review — {area.display_name}")
    print(f"  generated {review['generated_at']} against {review['net_file']}")
    print(f"  SUMO {review['sumo_version']}")

    wanted = args.section or list(SECTIONS)
    renderers = {
        "operational": _operational,
        "boundary": _boundary,
        "tls": _tls,
        "ramps": _ramps,
        "junctions": _junctions,
        "defaults": _defaults,
    }
    for section in SECTIONS:
        if section in wanted:
            renderers[section](review)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
