"""Audits of the network's estimated parameters: signal programs and speeds.

Neither audit changes anything. Both exist because Phase 3's results rest on
assumptions that are easy to forget once they are inside a `.net.xml`, and a
number that has been through a simulation looks like a measurement whether or not
it started as one.

The two audited here are the ones that most directly move the answer:

* **Signal programs** set how the junction discharges, and therefore queue length.
  Every program in this network was generated by netconvert from its defaults.
  **No real Bengaluru signal timing exists anywhere in this project.**
* **Free-flow speed** is the reference that time loss is measured against. SUMO
  supplied it on most edges, so reported time loss is an over-estimate wherever
  the default exceeds the real limit.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

from ems_sim.provenance import DataClass

SIGNAL_PROVENANCE = "ESTIMATED_DATA / NETCONVERT_GENERATED"

SIGNAL_BASIS = (
    "Every phase duration and cycle structure in this network was generated by "
    "netconvert from its built-in defaults. Signal LOCATIONS come from "
    "OpenStreetMap; TIMINGS do not exist in OSM and are not published for "
    "Bengaluru. These are not actual Silk Board signal timings and must never be "
    "described as such."
)


def audit_traffic_lights(net_file: Path) -> dict[str, Any]:
    """Enumerate every traffic-light program in the network.

    Reports what is there — counts, cycle lengths, phase durations, and how the
    green/yellow/red time divides — so the assumption is visible as a table
    rather than buried in XML.
    """
    root = ET.parse(net_file).getroot()
    programs: list[dict[str, Any]] = []

    for logic in root.findall("tlLogic"):
        phases = logic.findall("phase")
        durations = [float(p.get("duration", 0)) for p in phases]
        cycle = sum(durations)

        detail = []
        green = yellow = all_red = 0.0
        for phase, duration in zip(phases, durations, strict=True):
            state = phase.get("state", "")
            kind = _phase_kind(state)
            detail.append(
                {
                    "state": state,
                    "duration_s": duration,
                    "kind": kind,
                    "min_dur_s": (float(phase.get("minDur")) if phase.get("minDur") else None),
                    "max_dur_s": (float(phase.get("maxDur")) if phase.get("maxDur") else None),
                }
            )
            if kind == "green":
                green += duration
            elif kind == "yellow":
                yellow += duration
            elif kind == "all_red":
                all_red += duration

        programs.append(
            {
                "tls_id": logic.get("id"),
                "program_id": logic.get("programID"),
                "type": logic.get("type"),
                "offset_s": float(logic.get("offset", 0)),
                "phase_count": len(phases),
                "cycle_length_s": round(cycle, 1),
                "green_time_s": round(green, 1),
                "yellow_time_s": round(yellow, 1),
                "all_red_time_s": round(all_red, 1),
                # Green summed across phases over the cycle. This says how much
                # of the cycle is NOT interphase — it is near 0.9 for any sane
                # program and says nothing about how much green an approach gets.
                "non_interphase_fraction": round(green / cycle, 4) if cycle else None,
                # The figure that matters: what share of the cycle each signal
                # group is actually given green. A movement's capacity is its own
                # green share, not the cycle's.
                "green_share_per_signal_group": _green_share_per_group(phases, durations, cycle),
                "signal_group_count": len(phases[0].get("state", "")) if phases else 0,
                "phases": detail,
            }
        )

    cycles = [p["cycle_length_s"] for p in programs]
    return {
        "data_class": SIGNAL_PROVENANCE,
        "basis": SIGNAL_BASIS,
        "traffic_light_count": len(programs),
        "all_static": all(p["type"] == "static" for p in programs),
        "cycle_lengths_s": sorted(set(cycles)),
        "uniform_cycle_length": len(set(cycles)) == 1,
        "phase_counts": sorted({p["phase_count"] for p in programs}),
        "total_signal_groups": sum(p["signal_group_count"] for p in programs),
        "programs": sorted(programs, key=lambda p: -p["phase_count"]),
        "consequence": (
            "Signal timing sets how much traffic a junction discharges per cycle, "
            "which sets queue length, which is what this project reports. Because "
            "every program here is a netconvert default, the junction's discharge "
            "behaviour is assumed rather than observed, and every delay figure "
            "computed on this network inherits that assumption."
        ),
        "phase5_note": (
            "Phase 5's EMS priority policy actuates these programs. The recovered "
            "time it measures will be relative to this assumed baseline timing, not "
            "to how Silk Board is actually signalled."
        ),
    }


def _green_share_per_group(phases: list, durations: list[float], cycle: float) -> dict[str, Any]:
    """Green share of the cycle for each signal group.

    SUMO's phase ``state`` has one character per signal group, so a group's green
    time is the sum of the durations of the phases in which its character is G or
    g. That share is what sets the movement's capacity; the cycle-wide green sum
    does not.
    """
    if not phases or not cycle:
        return {}
    width = len(phases[0].get("state", ""))
    shares = []
    for index in range(width):
        green = sum(
            duration
            for phase, duration in zip(phases, durations, strict=True)
            if index < len(phase.get("state", "")) and phase.get("state", "")[index] in "Gg"
        )
        shares.append(round(green / cycle, 4))
    if not shares:
        return {}
    return {
        "signal_groups": width,
        "min": min(shares),
        "max": max(shares),
        "mean": round(sum(shares) / len(shares), 4),
        "shares": shares,
    }


def _phase_kind(state: str) -> str:
    """Classify a SUMO phase state string.

    SUMO encodes one character per signal group: G/g green, y yellow, r red.
    """
    if not state:
        return "unknown"
    lowered = state.lower()
    if "y" in lowered:
        return "yellow"
    if "g" in lowered:
        return "green"
    if set(lowered) <= {"r", "o", "u", "s"}:
        return "all_red"
    return "other"


def audit_speeds(net_file: Path) -> dict[str, Any]:
    """Separate OSM-derived from SUMO-supplied speeds, edge by edge.

    The ≥80 km/h group gets its own listing because those are the edges where the
    free-flow reference is most likely wrong, and free-flow is what delay is
    measured against.

    Nothing is replaced. No source in this project supports a better value, and a
    guess would be worse than a labelled default — it would look sourced.
    """
    root = ET.parse(net_file).getroot()

    defaults: dict[str, str] = {}
    for edge in root.findall("edge"):
        if edge.get("function") == "internal":
            continue
        for param in edge.findall("param"):
            if param.get("key") == "osmDefaults":
                defaults[edge.get("id")] = param.get("value", "")

    osm_rows: list[dict[str, Any]] = []
    sumo_rows: list[dict[str, Any]] = []
    by_class: dict[str, dict[str, Any]] = {}

    for edge in root.findall("edge"):
        if edge.get("function") == "internal":
            continue
        lanes = edge.findall("lane")
        if not lanes:
            continue
        edge_id = edge.get("id")
        speed_ms = float(lanes[0].get("speed"))
        speed_kmh = round(speed_ms * 3.6, 1)
        edge_class = edge.get("type") or "unknown"
        length = round(sum(float(lane.get("length", 0)) for lane in lanes) / len(lanes), 1)
        estimated = "speed" in defaults.get(edge_id, "")

        row = {
            "edge_id": edge_id,
            "edge_class": edge_class,
            "name": edge.get("name"),
            "speed_kmh": speed_kmh,
            "lane_count": len(lanes),
            "length_m": length,
            "speed_provenance": (
                str(DataClass.ESTIMATED) if estimated else str(DataClass.PUBLICLY_SOURCED)
            ),
            "speed_source": (
                "netconvert built-in type map" if estimated else "OpenStreetMap maxspeed tag"
            ),
        }
        (sumo_rows if estimated else osm_rows).append(row)

        bucket = by_class.setdefault(
            edge_class,
            {
                "edge_class": edge_class,
                "edges": 0,
                "osm_speed_edges": 0,
                "sumo_speed_edges": 0,
                "speeds_kmh": set(),
            },
        )
        bucket["edges"] += 1
        bucket["speeds_kmh"].add(speed_kmh)
        bucket["sumo_speed_edges" if estimated else "osm_speed_edges"] += 1

    for bucket in by_class.values():
        bucket["speeds_kmh"] = sorted(bucket["speeds_kmh"])

    high = sorted(
        (r for r in sumo_rows if r["speed_kmh"] >= 80.0),
        key=lambda r: (-r["speed_kmh"], -r["length_m"]),
    )
    high_by_class: dict[str, int] = {}
    for row in high:
        high_by_class[row["edge_class"]] = high_by_class.get(row["edge_class"], 0) + 1

    return {
        "total_edges": len(osm_rows) + len(sumo_rows),
        "osm_derived": {
            "data_class": str(DataClass.PUBLICLY_SOURCED),
            "description": (
                "Speed present as an OpenStreetMap maxspeed tag and carried through "
                "conversion unchanged. Community-mapped, not independently verified."
            ),
            "edge_count": len(osm_rows),
            "edges": sorted(osm_rows, key=lambda r: -r["length_m"]),
        },
        "sumo_estimated": {
            "data_class": str(DataClass.ESTIMATED),
            "description": (
                "Speed supplied by netconvert's built-in type map because "
                "OpenStreetMap had none. SUMO cannot simulate an edge without one. "
                "Not a property of the real road."
            ),
            "edge_count": len(sumo_rows),
            "edges": sorted(sumo_rows, key=lambda r: -r["length_m"])[:400],
            "edges_truncated": max(0, len(sumo_rows) - 400),
        },
        "by_edge_class": sorted(by_class.values(), key=lambda b: -b["edges"]),
        "high_speed_defaults": {
            "threshold_kmh": 80.0,
            "count": len(high),
            "by_edge_class": high_by_class,
            "total_length_km": round(sum(r["length_m"] for r in high) / 1000, 2),
            "named_roads": sorted({r["name"] for r in high if r["name"]}),
            "edges": high,
            "why_it_matters": (
                "Time loss is measured against free-flow speed. Where the default "
                "exceeds the real limit, reported time loss on that edge is an "
                "over-estimate. netconvert's type map is derived from European "
                "conventions and assigns 100 km/h to highway.secondary, which in "
                "Bengaluru is an urban arterial."
            ),
            "not_replaced_because": (
                "No source in this project supports a better value. Substituting a "
                "guess would be worse than a labelled default: the guess would look "
                "sourced, and its provenance would be lost."
            ),
        },
    }
