"""Run the same scenario under several deterministic seeds.

A single simulation run answers "what happened this time". Five runs that differ
only in the random stream answer something more useful: **how much of the result
is the scenario, and how much is the draw.**

That distinction is what Phase 5 needs. A counterfactual reports a difference
between two runs; if the baseline itself moves by more than that difference when
only the seed changes, the difference is noise. Establishing the spread now,
before any policy exists, is the only way to know later whether a recovered time
is real.

What this does **not** establish: whether any of it resembles Bengaluru. Seed
variance measures the model's internal variability, not its external validity.
The demand, the vehicle behaviour and the signal programs are the same
assumptions in all five runs, and running them five times does not make them
observations.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from ems_sim.calibration.scenario import (
    DEFAULT_VARIANT,
    UNRESOLVED_EDGE_IDS,
    ScenarioVariant,
    ensure_variant_network,
)
from ems_sim.demand.ambulance import AmbulanceTripConfig
from ems_sim.demand.config import DemandConfig
from ems_sim.demand.generator import generate_demand
from ems_sim.runner.sumo_env import SumoInstallation, require_sumo
from ems_sim.runner.sumo_process import SumoRunOptions
from ems_sim.runner.traci_bridge import (
    enrich_from_statistics,
    enrich_from_tripinfo,
    run_baseline,
)

DEFAULT_SEEDS: tuple[int, ...] = (42, 43, 44, 45, 46)
"""Documented default seed set. Any values would do; what matters is that they
are recorded, so a spread can be reproduced rather than approximated."""


@dataclass
class EdgeMeasurement:
    """Aggregated measurements for one edge, from SUMO's edgeData output."""

    edge_id: str
    sampled_seconds: float = 0.0
    density: float | None = None
    occupancy: float | None = None
    waiting_time_s: float | None = None
    time_loss_s: float | None = None
    speed_ms: float | None = None
    departed: int = 0
    arrived: int = 0
    entered: int = 0
    left: int = 0

    def as_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class SeedRunResult:
    """Everything one seeded run produced."""

    seed: int
    demand_id: str
    demand_config_hash: str
    variant_id: str

    departed: int = 0
    arrived: int = 0
    remaining: int = 0
    loaded: int = 0
    backlog: int = 0
    teleports: int = 0
    sumo_teleports: int | None = None
    collisions: int = 0

    mean_travel_time_s: float | None = None
    mean_waiting_time_s: float | None = None
    mean_time_loss_s: float | None = None
    mean_speed_ms: float | None = None
    mean_route_length_m: float | None = None
    completed_trips: int = 0

    ambulance_completed: bool = False
    ambulance_travel_time_s: float | None = None
    ambulance_waiting_time_s: float | None = None
    ambulance_time_loss_s: float | None = None
    ambulance_route_edges: list[str] = field(default_factory=list)
    ambulance_route_length_m: float | None = None
    ambulance_used_unresolved: bool = False

    vehicles_using_unresolved: int = 0
    wall_clock_s: float = 0.0
    output_dir: str = ""

    top_delay_edges: list[dict[str, Any]] = field(default_factory=list)
    top_waiting_edges: list[dict[str, Any]] = field(default_factory=list)
    intersection_approach_delay: list[dict[str, Any]] = field(default_factory=list)

    def as_dict(self) -> dict[str, Any]:
        return asdict(self)


def _edge_data_additional_file(destination: Path, period_s: float, output: Path) -> Path:
    """Write the additional-file that asks SUMO for aggregated edge measurements.

    Edge-level figures are not available from the trip outputs: they describe
    vehicles, not places. Attributing delay to a location — which is what Phase 6
    will need — requires SUMO to aggregate per edge as it runs.
    """
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        "\n".join(
            [
                "<?xml version='1.0' encoding='UTF-8'?>",
                "<!-- Generated by ems_sim.calibration.multi_seed. Asks SUMO for",
                "     per-edge aggregated measurements over the whole run. -->",
                "<additional>",
                f'    <edgeData id="edges" freq="{period_s:.0f}" file="{output.name}"'
                ' excludeEmpty="true"/>',
                "</additional>",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    return destination


def _parse_edge_data(path: Path) -> dict[str, EdgeMeasurement]:
    """Read SUMO's edgeData output.

    Intervals are summed rather than averaged where the quantity is a total
    (waiting time, counts) and duration-weighted where it is a rate (speed,
    density), because averaging a total across intervals would understate it.
    """
    if not path.is_file():
        return {}
    root = ET.parse(path).getroot()
    measurements: dict[str, EdgeMeasurement] = {}

    for interval in root.findall("interval"):
        begin = float(interval.get("begin", 0))
        end = float(interval.get("end", 0))
        span = max(end - begin, 0.0)
        for edge in interval.findall("edge"):
            edge_id = edge.get("id")
            record = measurements.setdefault(edge_id, EdgeMeasurement(edge_id=edge_id))

            record.sampled_seconds += span
            for attribute, field_name in (
                ("waitingTime", "waiting_time_s"),
                ("timeLoss", "time_loss_s"),
            ):
                raw = edge.get(attribute)
                if raw is not None:
                    value = float(raw)
                    current = getattr(record, field_name) or 0.0
                    setattr(record, field_name, current + value)
            for attribute, field_name in (
                ("density", "density"),
                ("occupancy", "occupancy"),
                ("speed", "speed_ms"),
            ):
                raw = edge.get(attribute)
                if raw is not None:
                    value = float(raw)
                    current = getattr(record, field_name)
                    setattr(
                        record,
                        field_name,
                        value if current is None else (current + value) / 2,
                    )
            for attribute, field_name in (
                ("departed", "departed"),
                ("arrived", "arrived"),
                ("entered", "entered"),
                ("left", "left"),
            ):
                value = edge.get(attribute)
                if value is not None:
                    setattr(record, field_name, getattr(record, field_name) + int(value))
    return measurements


def _intersection_approach_delay(
    edges: dict[str, EdgeMeasurement], net_file: Path, installation: SumoInstallation
) -> list[dict[str, Any]]:
    """Roll edge delay up to the junction each edge leads into.

    An approach edge's delay attributes to the junction downstream of it: that is
    the unit an intervention would target, and the one Phase 5's signal policy
    will act on.
    """
    import sys

    tools = str(installation.tools_dir)
    if tools not in sys.path:
        sys.path.insert(0, tools)
    import sumolib  # noqa: PLC0415

    net = sumolib.net.readNet(str(net_file), withInternal=False)
    by_junction: dict[str, dict[str, Any]] = {}
    for edge_id, record in edges.items():
        try:
            edge = net.getEdge(edge_id)
        except KeyError:
            continue
        junction = edge.getToNode()
        entry = by_junction.setdefault(
            junction.getID(),
            {
                "junction_id": junction.getID(),
                "is_traffic_light": junction.getType()
                in ("traffic_light", "traffic_light_right_on_red"),
                "approach_edges": 0,
                "total_time_loss_s": 0.0,
                "total_waiting_time_s": 0.0,
                "road_names": set(),
            },
        )
        entry["approach_edges"] += 1
        entry["total_time_loss_s"] += record.time_loss_s or 0.0
        entry["total_waiting_time_s"] += record.waiting_time_s or 0.0
        if edge.getName():
            entry["road_names"].add(edge.getName())

    rows = []
    for entry in by_junction.values():
        entry["road_names"] = sorted(entry["road_names"])
        entry["total_time_loss_s"] = round(entry["total_time_loss_s"], 1)
        entry["total_waiting_time_s"] = round(entry["total_waiting_time_s"], 1)
        rows.append(entry)
    return sorted(rows, key=lambda r: -r["total_time_loss_s"])


def run_seed(
    seed: int,
    base_config: DemandConfig,
    ambulance: AmbulanceTripConfig,
    repo_root: Path,
    study_area,
    variant: ScenarioVariant = DEFAULT_VARIANT,
    area_id: str = "silk_board_v1",
    installation: SumoInstallation | None = None,
    edge_data_period_s: float = 300.0,
    top_n: int = 25,
    vtype_overrides: dict[str, dict[str, float | str]] | None = None,
) -> SeedRunResult:
    """Run the scenario once with one seed."""
    from dataclasses import replace

    installation = installation or require_sumo()
    net_file = ensure_variant_network(variant, study_area, repo_root, installation)

    config = replace(
        base_config,
        seed=seed,
        demand_id=f"{base_config.demand_id.rsplit('_seed', 1)[0]}_seed{seed}{variant.net_suffix}",
    )
    demand = generate_demand(config, ambulance, net_file, repo_root, installation, vtype_overrides)

    output_dir = repo_root / "simulation" / "results" / config.demand_id
    output_dir.mkdir(parents=True, exist_ok=True)
    edge_output = output_dir / "edgedata.xml"
    additional = _edge_data_additional_file(
        output_dir / "edgedata.add.xml", edge_data_period_s, edge_output
    )

    options = SumoRunOptions(
        net_file=net_file,
        route_files=(demand.routes_file,),
        begin_s=config.begin_s,
        end_s=config.end_s,
        step_length_s=config.step_length_s,
        seed=seed,
        tripinfo_output=output_dir / "tripinfo.xml",
        summary_output=output_dir / "summary.xml",
        statistic_output=output_dir / "statistics.xml",
        queue_output=output_dir / "queues.xml",
        extra={"additional-files": str(additional)},
    )
    measurements = run_baseline(options, ambulance.vehicle_id, installation, sample_interval_s=30.0)
    enrich_from_statistics(measurements, output_dir / "statistics.xml")
    enrich_from_tripinfo(measurements, output_dir / "tripinfo.xml")

    completed = [t for t in measurements.trips.values() if t.arrival_s is not None]

    def mean(values: list[float]) -> float | None:
        clean = [v for v in values if v is not None]
        return round(sum(clean) / len(clean), 3) if clean else None

    edges = _parse_edge_data(edge_output)
    ranked_delay = sorted(edges.values(), key=lambda e: -(e.time_loss_s or 0.0))[:top_n]
    ranked_waiting = sorted(edges.values(), key=lambda e: -(e.waiting_time_s or 0.0))[:top_n]

    unresolved = set(UNRESOLVED_EDGE_IDS)
    using_unresolved = sum(
        1 for t in measurements.trips.values() if unresolved & set(t.route_edges)
    )
    ambulance_trip = measurements.trips.get(ambulance.vehicle_id)

    return SeedRunResult(
        seed=seed,
        demand_id=config.demand_id,
        demand_config_hash=config.config_hash(),
        variant_id=variant.variant_id,
        departed=measurements.departed,
        arrived=measurements.arrived,
        remaining=measurements.still_running_at_end,
        loaded=measurements.loaded,
        backlog=measurements.insertion_backlog_at_end,
        teleports=len(measurements.teleports),
        sumo_teleports=measurements.sumo_reported_teleports,
        collisions=measurements.collisions,
        mean_travel_time_s=mean([t.travel_time_s for t in completed]),
        mean_waiting_time_s=mean([t.waiting_time_s for t in completed]),
        mean_time_loss_s=mean([t.time_loss_s for t in completed]),
        mean_route_length_m=mean([t.route_length_m for t in completed]),
        completed_trips=len(completed),
        ambulance_completed=(ambulance_trip is not None and ambulance_trip.arrival_s is not None),
        ambulance_travel_time_s=ambulance_trip.travel_time_s if ambulance_trip else None,
        ambulance_waiting_time_s=(ambulance_trip.waiting_time_s if ambulance_trip else None),
        ambulance_time_loss_s=ambulance_trip.time_loss_s if ambulance_trip else None,
        ambulance_route_edges=(ambulance_trip.route_edges if ambulance_trip else []),
        ambulance_route_length_m=(ambulance_trip.route_length_m if ambulance_trip else None),
        ambulance_used_unresolved=bool(
            ambulance_trip and unresolved & set(ambulance_trip.route_edges)
        ),
        vehicles_using_unresolved=using_unresolved,
        wall_clock_s=round(measurements.wall_clock_s, 2),
        # Repo-relative. An absolute path would embed the machine it ran on into
        # a committed artefact, making the file non-portable and adding diff
        # churn on every other machine.
        output_dir=str(output_dir.relative_to(repo_root)),
        top_delay_edges=[e.as_dict() for e in ranked_delay],
        top_waiting_edges=[e.as_dict() for e in ranked_waiting],
        intersection_approach_delay=_intersection_approach_delay(edges, net_file, installation)[
            :top_n
        ],
    )
